### PR TITLE
Upgrades to pandas and pyarrow version

### PR DESCRIPTION
**Pull request by elanqo**
Upgrades to increase pandas and pyarrow version. This PR addresses issue https://github.com/jaysnm/dremio-arrow/issues/3

### CODE REVIEW

**Comment by jaysnm** [comment]
Dear Emmanuel,

Thank you for making time to contribute to this repo. I have run CI checks and none passed due to incompatibility between lock file and poetry version in use on the CI. Will regenerate the lock file and clean the code-base before we can have this PR merged.

**Comment by elanqo** [comment]
Thanks

**Comment by elanqo** [comment]
Hallow @jaysnm, sorry to bother you. Do you have SLA when you will be able to fix .lock file.

**Comment by jaysnm** [comment]
Dear Emmanuel

I have updated the lock-file, bumped dependencies and updated the docs. I also released a patch version 1.0.3 with bumped dependencies. 

I will go ahead and close this PR as it conflicts with main.

Next step will be creating package roadmap and updating contributors guide.  Feel free to add your thoughts on roadmap and contributors guide on issue #5

**Pull request closed without merging**
